version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}

      APP_PORT: ${APP_PORT}
      DEBUG: ${DEBUG}
    ports:
      - "8000:8000"
    networks:
      - app_network

    frontend:
      build: ./frontend
      container_name: react_frontend
      restart: always
      ports:
        - "3000:3000"
      networks:
        - app_network

volumes:
  mysql_data:

networks:
  app_network: