services:

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}

      REDIS_HOST: redis
      REDIS_PORT: 6379

      APP_PORT: ${APP_PORT}
      DEBUG: ${DEBUG}
    ports:
      - "8000:8000"
    networks:
      - app_network

  celery-worker:
    build: ./backend
    container_name: celery_worker
    restart: always
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CRAWL_COUNTRY_CODE: LK
      CRAWL_DEMO_MODE: "true"
      CRAWL_SCHEDULER_TICK_SECONDS: 30
      CRAWL_DEMO_INTERVAL_STARTER: 120
      CRAWL_DEMO_INTERVAL_GROWTH: 60
      CRAWL_DEMO_INTERVAL_ENTERPRISE: 30
    command: >
      celery -A app.core.celery.celery worker
      -P solo --loglevel=info --include=app.tasks.crawl_tasks
    networks:
      - app_network

  celery-beat:
    build: ./backend
    container_name: celery_beat
    restart: always
    depends_on:
      - mysql
      - redis
      - celery-worker
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CRAWL_COUNTRY_CODE: LK
      CRAWL_DEMO_MODE: "true"
      CRAWL_SCHEDULER_TICK_SECONDS: 30
      CRAWL_DEMO_INTERVAL_STARTER: 120
      CRAWL_DEMO_INTERVAL_GROWTH: 60
      CRAWL_DEMO_INTERVAL_ENTERPRISE: 30
    command: celery -A app.core.celery.celery beat --loglevel=info
    networks:
      - app_network

  flower:
    build: ./backend
    container_name: flower_dashboard
    restart: always
    depends_on:
      - redis
      - celery-worker
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: celery -A app.core.celery.celery flower --port=5555
    ports:
      - "5555:5555"
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
